# Generated by Django 6.0.6 on 2026-06-12 02:11

from django.db import migrations

def populate_initial_products(apps, schema_editor):
    """
    Populates the database with initial product categories and products.
    """
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    # Se ha vaciado esta función. La carga de productos se hará ahora
    # a través de la aplicación o el admin de Django para poder subir
    # las imágenes a Azure Blob Storage.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_products),
    ]